[workspace]
resolver = "2"

members = [
    "catacomb",
    "crates/ipc",
    "jolly/crates/core",
    "jolly/crates/ui",
    "jolly/apps/home",
    "jolly/apps/nav",
    "jolly/apps/settings",
    "jolly-launcher",
]
