[package]
name = "debug_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
catacomb_ipc = { path = "../../crates/ipc", features = ["clap"] }
clap = { version = "4.2.3", features = ["derive"] }
serde_json = "1.0.85"

[lints.rust]
warnings = "deny"
