[package]
name = "jolly-home"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8"
jollypad-core = { path = "../../crates/core" }
jollypad-ui-kit = { path = "../../crates/ui-kit" }
log = "0.4"
env_logger = "0.10"
gilrs = "0.10"

[build-dependencies]
slint-build = "1.8"
